### ISSUE TITLE
Change

### ISSUE THREAD

**Issue by chunrui-qashier** [JiaQi0830/carpark-lots#1]
@JiaQi0830 Could you try to optimize below variables definition? 

https://github.com/JiaQi0830/carpark-lots/blob/7e396a32163848bdcfabecbcd1e6fba648ed6144/src/components/Carpark.vue#L6

For the initial value of maximum available, do you have a better choice? 

https://github.com/JiaQi0830/carpark-lots/blob/7e396a32163848bdcfabecbcd1e6fba648ed6144/src/components/Carpark.vue#L40

**Comment by JiaQi0830** [comment]
https://github.com/JiaQi0830/carpark-lots/commit/52996e9cbc2993798c4b595651a00369b65de208
@chunrui-qashier for the carpark, it is a mistake unused variable that I forget to clean out. I have updated the max value in the commit above.
